# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160710_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('code', models.CharField(max_length=2, verbose_name='код')),
            ],
            options={
                'verbose_name_plural': 'отделы',
                'verbose_name': 'отдел',
                'db_table': 'department',
            },
        ),
    ]
