# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20160829_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Department', verbose_name='отдел'),
        ),
    ]
